#!/usr/bin/env python3

import argparse
from pathlib import Path
import subprocess
import sys

def get_args():
    argparser = argparse.ArgumentParser(prog="iodine", add_help=False)
    argparser.add_argument("-b", "--build", action="store_true")
    argparser.add_argument("--profile", action="store_true")
    args, unknown_args = argparser.parse_known_args()
    for i, arg in enumerate(unknown_args):
        p = Path(arg)
        if p.is_file():
            unknown_args[i] = p.resolve()
    return args, unknown_args

args, unknown_args = get_args()

THIS_DIR = Path(__file__).resolve().parent
IVERILOG_DIR = THIS_DIR / "iverilog-parser"
STACK_BUILD_CMD = ["stack", "build"]
STACK_RUN_CMD = ["stack", "exec", "iodine"]
STACK_PROFILE_ARGS = ["--profile", "--work-dir", ".stack-work-profile"] if args.profile else []

if args.build:
    cmd = STACK_BUILD_CMD + STACK_PROFILE_ARGS
else:
    cmd = STACK_RUN_CMD + STACK_PROFILE_ARGS
    cmd += ["--", "--iverilog-dir", IVERILOG_DIR]
    cmd += unknown_args

# print(" ".join(str(a) for a in cmd))
r = subprocess.run(cmd, cwd=THIS_DIR)
sys.exit(r.returncode)
