name:                verylog-hs
version:             0.1.0.0
github:              "gokhankici/verylog-hs"
license:             MIT
author:              "Rami Gokhan Kici"
maintainer:          "gokhankici@gmail.com"
copyright:           "2018 Rami Gokhan Kici"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Generates the transition relation & verification conditions from a Verilog IR
category:            Hardware Verification

description:         Please see the README on Github at <https://github.com/gokhankici/verylog-hs#readme>

dependencies:
- base >= 4.7 && < 5
- array
- cmdargs
- containers
- directory
- filepath
- lens
- megaparsec
- mtl
- pretty
- process
- semigroups
- unordered-containers
- ansi-terminal
- liquid-fixpoint
- deepseq
- hashable

library:
  source-dirs:           src
  ghc-options:
  - -Wall -Wno-missing-signatures -Wno-orphans -Wno-name-shadowing -O2
  exposed-modules:
  - Verylog.MainCommon
  - Verylog.FPGen
  - Verylog.Language.Parser
  - Verylog.Language.Types
  - Verylog.Transform.TransitionRelation
  - Verylog.Transform.Utils
  - Verylog.Transform.VCGen
  - Verylog.Transform.Modularize
  - Verylog.Solver.Common
  - Verylog.Solver.FP.Types

executables:
  vcgen-fp:
    main:                Main.hs
    source-dirs:         app-fp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall 
    - -O2
    dependencies:
    - verylog-hs

tests:
  vcgen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall 
    - -O2
    dependencies:
    - verylog-hs
