name:                verylog-hs
version:             0.1.0.0
github:              "gokhankici/verylog-hs"
license:             MIT
author:              "Rami Gokhan Kici"
maintainer:          "gokhankici@gmail.com"
copyright:           "2018 Rami Gokhan Kici"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Generates the transition relation & verification conditions from a Verilog IR
category:            Hardware Verification

description:         Please see the README on Github at <https://github.com/gokhankici/verylog-hs#readme>

dependencies:
- base >= 4.7 && < 5
- array
- cmdargs
- containers
- directory
- filepath
- lens
- megaparsec
- mtl
- pretty
- process
- semigroups
- unordered-containers
- ansi-terminal

library:
  source-dirs:           src
  ghc-options:
  - -W -Werror
  exposed-modules:
  - Verylog.MainCommon
  - Verylog.HSFGen
  - Verylog.SMTGen
  - Verylog.FPGen
  - Verylog.Language.Parser
  - Verylog.Language.Types
  - Verylog.Transform.TransitionRelation
  - Verylog.Transform.Utils
  - Verylog.Transform.VCGen
  - Verylog.Solver.HSF.Types
  - Verylog.Solver.SMT.Types
  - Verylog.Solver.FP.Types
  - SMT2FP.SMT.Parser
  - SMT2FP.Fixpoint.Types
  - SMT2FP.Fixpoint.Transform

executables:
  vcgen-hsf:
    main:                Main.hs
    source-dirs:         app-hsf
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W -Werror
    dependencies:
    - verylog-hs
  vcgen-smt:
    main:                Main.hs
    source-dirs:         app-smt
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W -Werror
    dependencies:
    - verylog-hs
  vcgen-fp:
    main:                Main.hs
    source-dirs:         app-fp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W -Werror
    dependencies:
    - verylog-hs
  smt2fp:
    main:                Main.hs
    source-dirs:         app-smt2fp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W -Werror
    dependencies:
    - verylog-hs
    - ansi-terminal

tests:
  vcgen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W -Werror
    dependencies:
    - verylog-hs
