#!/usr/bin/env python3

import argparse
from   collections import namedtuple
from   pathlib import Path
import subprocess
import sys

THIS_DIR = Path(__file__).resolve().parent
IVERILOG_DIR = THIS_DIR / "iverilog-parser"

class Test(namedtuple("Test", ["verilog_file", "module_name", "annotation_file"])):
    def run(self):
        args = [self.verilog_file, self.module_name, self.annotation_file]
        r = subprocess.run(["stack", "exec", "iodine", "--",
                            "--iverilog-dir", IVERILOG_DIR] +
                           args,
                           cwd=THIS_DIR)
        return r.returncode


CONFIG = {
        "ALU": Test(
            Path.home() / "play/ucb-bar/modules/ALU.v",
            "ALU",
            Path.home() / "play/ucb-bar/modules/ALU.json"
            )
        }

def get_test():
    ap = argparse.ArgumentParser()
    ap.add_argument("testname", choices=CONFIG.keys())
    args = ap.parse_args()
    return CONFIG[args.testname]

if __name__ == "__main__":
    t = get_test()
    rc = t.run()
    sys.exit(rc)
